### PR TITLE
Feature/rename healthz middleware

### PR DESCRIPTION
**Pull request by meanin**

### CODE REVIEW

**Comment by wojciech12** [comment]
@meanin  @mmisztal1980 Guys, awesome work.

**Comment by meanin** [comment]
Not yet ready.

**Comment by wojciech12** [comment]
True, the PR is closed. Regarding the naming, I would prefer to have  /health or /heathz for liveness and another ready/ for readiness, just to make it explicit for a talk.

We can add in the readme that, according to C# best practices / C# community, you should go with certain naming convention with a link to the framework docs.

**Comment by meanin** [comment]
Sure, I've added in newer version handling for both `healthz` and `probe` in the same manner. Currently, I am working on a graceful shutdown on a SIGTERM.

**Pull request closed without merging**
